// Code generated by protoc-gen-go.
// source: auth.proto
// DO NOT EDIT!

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	User
	RegisterRequest
	RegisterResponse
	Certificate
	Result
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CertificateType int32

const (
	CertificateType_UUID     CertificateType = 0
	CertificateType_PLAIN    CertificateType = 1
	CertificateType_TOKEN    CertificateType = 2
	CertificateType_FACEBOOK CertificateType = 3
)

var CertificateType_name = map[int32]string{
	0: "UUID",
	1: "PLAIN",
	2: "TOKEN",
	3: "FACEBOOK",
}
var CertificateType_value = map[string]int32{
	"UUID":     0,
	"PLAIN":    1,
	"TOKEN":    2,
	"FACEBOOK": 3,
}

func (x CertificateType) String() string {
	return proto.EnumName(CertificateType_name, int32(x))
}
func (CertificateType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type User struct {
	UserId     uint64 `protobuf:"varint,1,opt,name=UserId,json=userId" json:"UserId,omitempty"`
	UserName   string `protobuf:"bytes,2,opt,name=UserName,json=userName" json:"UserName,omitempty"`
	Password   string `protobuf:"bytes,3,opt,name=Password,json=password" json:"Password,omitempty"`
	DeviceName string `protobuf:"bytes,4,opt,name=DeviceName,json=deviceName" json:"DeviceName,omitempty"`
	DeviceId   string `protobuf:"bytes,5,opt,name=DeviceId,json=deviceId" json:"DeviceId,omitempty"`
	DeviceType int32  `protobuf:"varint,6,opt,name=DeviceType,json=deviceType" json:"DeviceType,omitempty"`
	OpenUUID   string `protobuf:"bytes,7,opt,name=OpenUUID,json=openUUID" json:"OpenUUID,omitempty"`
	Lang       string `protobuf:"bytes,8,opt,name=Lang,json=lang" json:"Lang,omitempty"`
	LoginIP    string `protobuf:"bytes,9,opt,name=LoginIP,json=loginIP" json:"LoginIP,omitempty"`
	Created    int64  `protobuf:"varint,10,opt,name=Created,json=created" json:"Created,omitempty"`
	Updated    int64  `protobuf:"varint,11,opt,name=Updated,json=updated" json:"Updated,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RegisterRequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterResponse struct {
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Certificate struct {
	Type  CertificateType `protobuf:"varint,1,opt,name=Type,json=type,enum=auth.CertificateType" json:"Type,omitempty"`
	Proof []byte          `protobuf:"bytes,2,opt,name=Proof,json=proof,proto3" json:"Proof,omitempty"`
}

func (m *Certificate) Reset()                    { *m = Certificate{} }
func (m *Certificate) String() string            { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()               {}
func (*Certificate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Result struct {
	OK     bool   `protobuf:"varint,1,opt,name=OK,json=oK" json:"OK,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=UserId,json=userId" json:"UserId,omitempty"`
	Body   []byte `protobuf:"bytes,3,opt,name=Body,json=body,proto3" json:"Body,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*RegisterRequest)(nil), "auth.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "auth.RegisterResponse")
	proto.RegisterType((*Certificate)(nil), "auth.Certificate")
	proto.RegisterType((*Result)(nil), "auth.Result")
	proto.RegisterEnum("auth.CertificateType", CertificateType_name, CertificateType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AuthService service

type AuthServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*Result, error)
	Auth(ctx context.Context, in *Certificate, opts ...client.CallOption) (*Result, error)
}

type authServiceClient struct {
	c           client.Client
	serviceName string
}

func NewAuthServiceClient(serviceName string, c client.Client) AuthServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "auth"
	}
	return &authServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*Result, error) {
	req := c.c.NewRequest(c.serviceName, "AuthService.Register", in)
	out := new(Result)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Auth(ctx context.Context, in *Certificate, opts ...client.CallOption) (*Result, error) {
	req := c.c.NewRequest(c.serviceName, "AuthService.Auth", in)
	out := new(Result)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceHandler interface {
	Register(context.Context, *RegisterRequest, *Result) error
	Auth(context.Context, *Certificate, *Result) error
}

func RegisterAuthServiceHandler(s server.Server, hdlr AuthServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&AuthService{hdlr}, opts...))
}

type AuthService struct {
	AuthServiceHandler
}

func (h *AuthService) Register(ctx context.Context, in *RegisterRequest, out *Result) error {
	return h.AuthServiceHandler.Register(ctx, in, out)
}

func (h *AuthService) Auth(ctx context.Context, in *Certificate, out *Result) error {
	return h.AuthServiceHandler.Auth(ctx, in, out)
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x52, 0xed, 0x6e, 0xd3, 0x30,
	0x14, 0x25, 0xa9, 0x9b, 0xa6, 0xb7, 0xd5, 0x16, 0xae, 0x00, 0x59, 0xfb, 0x31, 0x55, 0xf9, 0x43,
	0xe1, 0xc7, 0x10, 0xe5, 0x01, 0x50, 0xd7, 0x0e, 0x29, 0x6a, 0xd5, 0x54, 0x66, 0x7d, 0x80, 0xac,
	0xf6, 0xb2, 0x48, 0x25, 0x0e, 0x89, 0x03, 0xea, 0x5b, 0xf1, 0x88, 0xe8, 0xda, 0x29, 0xfb, 0xe0,
	0x57, 0x7c, 0xce, 0xf1, 0xb9, 0xc9, 0x3d, 0x27, 0x00, 0x59, 0x6b, 0x1e, 0xae, 0xaa, 0x5a, 0x1b,
	0x8d, 0x8c, 0xce, 0xf1, 0x1f, 0x1f, 0xd8, 0xae, 0x51, 0x35, 0xbe, 0x83, 0x80, 0x9e, 0x89, 0xe4,
	0xde, 0xc4, 0x9b, 0x32, 0x11, 0xb4, 0x16, 0xe1, 0x05, 0x84, 0xc4, 0x6f, 0xb2, 0x1f, 0x8a, 0xfb,
	0x13, 0x6f, 0x3a, 0x14, 0x61, 0xdb, 0x61, 0xd2, 0xb6, 0x59, 0xd3, 0xfc, 0xd6, 0xb5, 0xe4, 0x3d,
	0xa7, 0x55, 0x1d, 0xc6, 0x4b, 0x80, 0xa5, 0xfa, 0x55, 0xec, 0x95, 0x75, 0x32, 0xab, 0x82, 0xfc,
	0xc7, 0x90, 0xd7, 0xe9, 0x89, 0xe4, 0x7d, 0xe7, 0x95, 0x1d, 0x7e, 0xf4, 0xde, 0x1e, 0x2b, 0xc5,
	0x83, 0x89, 0x37, 0xed, 0x9f, 0xbc, 0xc4, 0x90, 0x37, 0xad, 0x54, 0xb9, 0xdb, 0x25, 0x4b, 0x3e,
	0x70, 0x5e, 0xdd, 0x61, 0x44, 0x60, 0xeb, 0xac, 0xcc, 0x79, 0x68, 0x79, 0x76, 0xc8, 0xca, 0x1c,
	0x39, 0x0c, 0xd6, 0x3a, 0x2f, 0xca, 0x64, 0xcb, 0x87, 0x96, 0x1e, 0x1c, 0x1c, 0x24, 0x65, 0x51,
	0xab, 0xcc, 0x28, 0xc9, 0x61, 0xe2, 0x4d, 0x7b, 0x62, 0xb0, 0x77, 0x90, 0x94, 0x5d, 0x25, 0xad,
	0x32, 0x72, 0x4a, 0xeb, 0x60, 0xfc, 0x19, 0xce, 0x85, 0xca, 0x8b, 0xc6, 0xa8, 0x5a, 0xa8, 0x9f,
	0xad, 0x6a, 0x0c, 0x5e, 0x02, 0xa3, 0x50, 0x6c, 0x74, 0xa3, 0x19, 0x5c, 0xd9, 0x98, 0x29, 0x36,
	0x61, 0xf9, 0x18, 0x21, 0x7a, 0xb4, 0x34, 0x95, 0x2e, 0x1b, 0x15, 0x6f, 0x60, 0xb4, 0x50, 0xb5,
	0x29, 0xee, 0x8b, 0x7d, 0x66, 0x14, 0x7e, 0x00, 0x66, 0xb7, 0xa5, 0x11, 0x67, 0xb3, 0xb7, 0x6e,
	0xc4, 0x93, 0x0b, 0x24, 0x0a, 0x66, 0x68, 0xfd, 0x37, 0xd0, 0xdf, 0xd6, 0x5a, 0xdf, 0xdb, 0x3e,
	0xc6, 0xa2, 0x5f, 0x11, 0x88, 0x97, 0x10, 0x08, 0xd5, 0xb4, 0x07, 0x83, 0x67, 0xe0, 0xa7, 0x2b,
	0x3b, 0x28, 0x14, 0xbe, 0x5e, 0x3d, 0xa9, 0xd6, 0x7f, 0x56, 0x2d, 0x02, 0xbb, 0xd6, 0xf2, 0x68,
	0xab, 0x1b, 0x0b, 0x76, 0xa7, 0xe5, 0xf1, 0xe3, 0x57, 0x38, 0x7f, 0xf1, 0x52, 0x0c, 0x81, 0x51,
	0xb2, 0xd1, 0x2b, 0x1c, 0x42, 0x7f, 0xbb, 0x9e, 0x27, 0x9b, 0xc8, 0xa3, 0xe3, 0x6d, 0xba, 0xba,
	0xd9, 0x44, 0x3e, 0x8e, 0x21, 0xfc, 0x36, 0x5f, 0xdc, 0x5c, 0xa7, 0xe9, 0x2a, 0xea, 0xcd, 0x72,
	0x18, 0xcd, 0x5b, 0xf3, 0xf0, 0x5d, 0xd5, 0x54, 0x17, 0x7e, 0x82, 0xf0, 0xb4, 0x39, 0x76, 0x4b,
	0xbd, 0x08, 0xef, 0x62, 0x7c, 0xa2, 0xed, 0xc7, 0xbf, 0x07, 0x46, 0x7e, 0x7c, 0xfd, 0x5f, 0x02,
	0xcf, 0x2f, 0xde, 0x05, 0xf6, 0x37, 0xfe, 0xf2, 0x37, 0x00, 0x00, 0xff, 0xff, 0x87, 0x79, 0x40,
	0x80, 0xd4, 0x02, 0x00, 0x00,
}
